---
title: "GEPD Microdata"
author: "Brian Stacy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.height = 6,
	fig.width = 8,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
library(haven)
library(vtable)
library(here)
library(readxl)
library(stringr)
library(Hmisc)
library(naniar)
library(lubridate)
library(skimr)
library(digest)
library(validate)
library(GGally)
library(Hmisc)
#Country name
country <-'PER'
country_name <- "Peru"
year <- '2019'
school_file <-'EPDash_v2.dta'
strata <- 
#########################
# File paths #
#########################
#The download_folder will be the location of where raw data is downloaded from the API
#The save_folder will be the location of where cleaned data is stored



if (str_to_lower(Sys.getenv("USERNAME")) == "wb469649" ){
  #project_folder  <- "//wbgfscifs01/GEDEDU/datalib-edu/projects/gepd"
  project_folder  <- "C:/Users/wb469649/WBG/HEDGE Files - HEDGE Documents/GEPD-Confidential/CNT/"
  download_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/raw/School", sep="/"))
  sampling_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/sampling", sep="/"))
  confidential_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/confidential/School", sep="/"))
  save_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/anonymized/School", sep="/"))
  backup_onedrive="no"
  save_folder_onedrive <- file.path(paste("C:/Users/wb469649/WBG/Ezequiel Molina - Dashboard (Team Folder)/Country_Work/",country_name,year,"Data/clean/School", sep="/"))
  
} else if  (str_to_lower(Sys.getenv("USERNAME")) == "wb577189" ){
  #project_folder  <- "//wbgfscifs01/GEDEDU/datalib-edu/projects/gepd"
  project_folder  <- "C:/Users/wb577189/OneDrive - WBG/GEPD-Confidential/CNT/"
  download_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/raw/School", sep="/"))
  sampling_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/sampling", sep="/"))
  confidential_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/confidential/School", sep="/"))
  save_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/anonymized/School", sep="/"))
  backup_onedrive="no"
  save_folder_onedrive <- file.path(paste("C:/Users/wb469649/WBG/Ezequiel Molina - Dashboard (Team Folder)/Country_Work/",country_name,year,"Data/clean/School", sep="/"))
  
}else {
  download_folder <- choose.dir(default = "", caption = "Select folder to open data downloaded from API")
  save_folder <- choose.dir(default = "", caption = "Select folder to save final data")

}


```


```{r functions}



#function to attach weights

df_weights_function <- function(dataset,scode, snumber, prov) {
  scode<-enquo(scode)  
  snumber<-enquo(snumber)
  prov<-enquo(prov)
  
  dataset %>%
    mutate(!! scode := as.numeric(.data$school_code)) %>%
    left_join(data_set_updated) %>%
    mutate(ipw=if_else(is.na(.data$weights), median(.data$weights, na.rm=T), .data$weights)*!! snumber ) %>%
    mutate(province=departamento) %>%
    select(-one_of(colnames(data_set_updated[, -which(names(data_set_updated) %in% c("rural","STRATUM", "STRATUM", 
                                                                                     "province"))])))
}

# anonymizer function

df_anon <- function(dataset) {
  temp<-get(dataset) 
    
    #add hashed school code if needed
    if ("school_code" %in% colnames(temp)) {
      temp <- temp %>%
        left_join(key) %>%
        select(hashed_school_code, hashed_school_province, hashed_school_district, everything())
    }
    
    
    #add on weights
    if ("school_code" %in% colnames(temp)) {
      temp <- df_weights_function(temp, codigo.modular, total_4th, departamento)
    }
    
    #Scrub names, geocodes
    temp <- temp %>%
      select(-starts_with('school_'), -one_of('m1s0q2_name', 'm1s0q2_code','m1s0q2_emis')) %>% # drop school names and address
      select(-starts_with('m1s0q9')) %>%
      select(-one_of('survey_time', 'lat','lon')) %>% #drop geo-codes
      select(-one_of('total_enrolled', 'm7saq8','m7saq10')) %>% 
      select(-one_of('m6_class_count')) %>% 
      select(-starts_with('enumerators_preload'), -one_of('m1s0q1_name', 'm1s0q1_name_other','m1s0q1_comments')) %>%  #get rid of enumerator names
      select(-one_of('m1saq1_first','m1saq1_last', 'm1saq2', 'm1saq2b')) %>% #drop principal names and phone numbers
      select(-contains('troster')) %>%
      select(-contains('name')) %>%
      select(-contains('_response')) %>%
      select(-contains('m2saq2')) %>%
      select(-contains('m6s1q1')) %>%
      select(-contains('m8s1q1')) %>%
      select(-contains('enumerators')) %>%
      select(-contains('m2saq2')) %>%
      select(-contains('m1saq1')) %>%
      select(-contains('phone')) %>%
      select(-contains('m1saq2')) %>%
      select(-contains('m7sb_troster')) %>%
      select(-contains('m3sb_troster')) %>%
      select(-contains('m3sb_etri')) %>%
      select(-contains('m5sb_troster')) %>%
      select(-contains('m6s1q1')) %>%
      select(-contains('m4saq1')) %>%
      select(-contains('m8s1q1')) %>%
      select(-contains('m4saq1_g2')) %>%
      select(-contains('comments')) %>%
      select(-contains('m1s0q1_name')) %>%
      select(-contains('m1s0q1_name_other')) %>%
      select(-contains('notekid')) 
    
    #Drop any "other" responses to questions
    temp <- temp %>%
      select(-contains('_other'))
    
    
    
    #convert # of students in school to categorical
    if ("m1saq7" %in% colnames(temp)) {
    temp <- temp %>%
      mutate(students_enrolled=case_when(
        m1saq7<25 ~ 1,
        m1saq7>=25 &  m1saq7<50 ~ 2,
        m1saq7>=50 &  m1saq7<75 ~ 3,
        m1saq7>=75 &  m1saq7<100 ~ 4,
        m1saq7>=100 &  m1saq7<150 ~ 5,
        m1saq7>=150 &  m1saq7<300 ~ 6,
        m1saq7>=300 &  m1saq7<500 ~ 7,
        m1saq7>=500  ~ 8
      )) %>%
      mutate(students_enrolled=factor(students_enrolled, levels=c(1,2,3,4,5,6,7,8), labels = c("Under 25", "25-50", "50-75", "75-100", "100-150", "150-300", "300-500", "Over 500"))) %>%
      select(-m1saq7)
    }
    
    if ("m1saq8" %in% colnames(temp)) {
    temp <- temp %>%
      mutate(boy_students_enrolled=case_when(
        m1saq8<25 ~ 1,
        m1saq8>=25 &  m1saq8<50 ~ 2,
        m1saq8>=50 &  m1saq8<75 ~ 3,
        m1saq8>=75 &  m1saq8<100 ~ 4,
        m1saq8>=100 &  m1saq8<150 ~ 5,
        m1saq8>=150 &  m1saq8<300 ~ 6,
        m1saq8>=300 &  m1saq8<500 ~ 7,
        m1saq8>=500  ~ 8
      ))  %>%
      mutate(boy_students_enrolled=factor(students_enrolled, levels=c(1,2,3,4,5,6,7,8), labels = c("Under 25", "25-50", "50-75", "75-100", "100-150", "150-300", "300-500", "Over 500"))) %>%
      select( -m1saq8)      
    }
    
    #return data
    temp
}

```

## Weights File

```{r}
#read in the file on school weights
#Load original sample of schools
currentDate<-c("2019-07-22")
sample_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/sampling/", sep="/"))
sample_frame_name <- paste(sample_folder,"/school_sample_",currentDate,".RData", sep="")

load(sample_frame_name)

key <- read_csv(file.path(confidential_folder, "EPDash_linkfile_hashed.csv"))
```


## School File

```{r school}

###########################
#read in school level file
###########################
school_dta<-read_dta(file.path(download_folder, school_file))


#rename a few key variables up front
school_dta<- school_dta %>%
  mutate(enumerator_name_other= m1s0q1_name_other  ,
         enumerator_number=if_else(!is.na(m1s0q1_name),m1s0q1_name, as.double(m1s0q1_number_other)) ,
         survey_time=m1s0q8,
         lat=m1s0q9__Latitude,
         lon=m1s0q9__Longitude,
         school_code=if_else(!is.na(school_code_preload),as.double(school_code_preload), as.double(m1s0q2_code)),
         m7_teach_count_pknw=m7_teach_count, #this variable was mistakenly not tagged as pknw
         total_enrolled=m1saq7) %>%
  mutate(school_code=if_else(school_code==0, 328328, school_code)) %>%
  mutate(school_code=if_else(school_code==62181, 558163, school_code))

school_micro_raw <- school_dta %>%
  group_by(school_code) %>%
  fill(everything(), .direction='downup') %>%
  slice(1) %>% 
  ungroup()


var.list <- sapply(school_dta, function(x) attr(x,"label"))
var.labels= unlist(var.list)

#add back labels
  
#add weights and anonymize
school_micro <- df_anon('school_micro_raw')                     

school_micro <- Hmisc::upData(school_micro, labels = var.labels)

write_dta(school_micro, path = paste0(save_folder, "/micro/school_micro_",country,"_",year,".dta"))                           
```
```{r}
#create a file for matching to tecaher and student files

#list additional info that will be useful to keep in each indicator dataframe
preamble_info <- c( 'interview__id', 'school_code',
                    'school_name_preload', 'school_address_preload', 
                    'school_province_preload', 'school_district_preload', 'school_code_preload', 'school_emis_preload',
                    'school_info_correct', 'm1s0q2_name', 'm1s0q2_code', 'm1s0q2_emis',
                    'survey_time', 'lat', 'lon', 'total_enrolled' , 'm7saq8', 'm7saq10'
)

drop_school_info <- c(
  
)

#Create a list of info to drop from final teacher files aggregated to school level. This will be necessary for merging these databases later

drop_teacher_info <- c( "questionnaire_roster__id", "teacher_name", "teacher_number", "available", 
                        "teacher_position", "teacher_grd1", "teacher_grd2", "teacher_grd3", "teacher_grd4", 
                        "teacher_grd5", "teacher_language", "teacher_math", "teacher_both_subj", "teacher_other_subj", 
                        "teacher_education", "teacher_year_began", "teacher_age" )


#create school database with just preamble info.  This will be useful for merging on school level info to some databases
school_data_preamble_temp <- school_dta %>%
  group_by(school_code) %>%
  select( preamble_info) %>%
  select(-interview__id) %>%
  summarise_all( ~(if(is.numeric(.)) mean(., na.rm = TRUE) else first(.))) 

school_data_preamble <- school_dta %>%
  group_by(interview__id) %>%
  select(interview__id, school_code) %>%
  left_join(school_data_preamble_temp)
```


## Teacher Questionnaire File

```{r}

teacher_questionnaire<-read_dta(file.path(download_folder, "questionnaire_roster.dta")) 

#Add school preamble info
teacher_questionnaire <- teacher_questionnaire %>%
  left_join(school_data_preamble) %>%
  select(preamble_info, everything())

#add weights and anonymize
teacher_questionnaire_micro <- df_anon('teacher_questionnaire')                     

write_dta(teacher_questionnaire_micro, path = paste0(save_folder, "/micro/teacher_questionnaire_micro","_",country,"_",year,".dta"))    
```


## Teacher Absence File

```{r}
############################
#read in teacher roster file
############################

teacher_absence_dta<-read_dta(file.path(download_folder, "questionnaire_selected.dta")) 

#Add school preamble info
teacher_absence_dta <- teacher_absence_dta %>%
  left_join(school_data_preamble) %>%
  select(preamble_info, everything()) 

#add weights and anonymize
teacher_absence_micro <- df_anon('teacher_absence_dta')                     


write_dta(teacher_absence_micro, path = paste0(save_folder, "/micro/teacher_absence_micro","_",country,"_",year,".dta"))    
```


## Teacher Assessment File

```{r teacherassess}
#read in data from difference questionnaire.  This was done because the exams were graded back in the central office.
school_dta_21<-read_dta(file.path(paste(download_folder,'version_21', sep="/"), "EPDash.dta"))

school_dta_21<- school_dta_21 %>%
  mutate(school_code=if_else(!is.na(school_code_preload),as.double(school_code_preload), as.double(m1s0q2_code))
  )

preamble_info_21 <- c('school_code' )

school_data_preamble_21<- school_dta_21 %>%
  select(interview__key, preamble_info_21)

teacher_assessment_dta_21<-read_dta(file.path(paste(download_folder,'version_21', sep="/"), "teacher_assessment_answers.dta"))

#Add school preamble info
teacher_assessment_dta <- teacher_assessment_dta_21 %>%
  left_join(school_data_preamble_21) %>%
  select(preamble_info_21, everything()) 

#add weights and anonymize
teacher_assessment_micro <- df_anon('teacher_assessment_dta')                     


write_dta(teacher_assessment_micro, path = paste0(save_folder, "/micro/teacher_assessment_micro","_",country,"_",year,".dta"))    
```



## Teacher Pedagogy File

```{r pedg}

#define variables for TEACH
# label variables

var.labels = c(route="Route ID", 
               school_clip="Clip Graded for each School",
               person = "Person Scoring",
               s_0_1_1 = "0.1 Teacher provides learning activity to most students",
               s_0_1_2 = "0.1 Students are on task",
               s_0_2_1 = "0.1 Teacher provides learning activity to most students",
               s_0_2_2 = "0.1 Students are on task",
               s_0_3_1 = "0.1 Teacher provides learning activity to most students",
               s_0_3_2 = "0.1 Students are on task",
               s_a1 = "SUPPORTIVE LEARNING ENVIRONMENT: Segment 1",
               s_a1_1 = "1.1 The teacher treats all students respectfully",
               s_a1_2 = "1.2 The teacher uses positive language with students",
               s_a1_3 = "1.3 The teacher responds to students' need",
               s_a1_4 = "1.4 The teacher does not exhibit gender bias and challenges gender stereotypes in the classroom",
               s_a2 = "POSITIVE BEHAVIORAL EXPECTATIONS: Segment 1",
               s_a2_1 = "2.1 The teacher sets clear behavioral expectations for classroom activities",
               s_a2_2 = "2.2 The teacher acknowledges positive student behavior",
               s_a2_3 = "2.3 The teacher redirects misbehavior and focuses on the expected behavior",
               s_b3 = "LESSON FACILITATION: Segment 1",
               s_b3_1 = "3.1 The teacher explicitly articulates the objectives of the lesson",
               s_b3_2 = "3.2 The teacher's explanation of content is clear",
               s_b3_3 = "3.3 The teacher makes connections in the lesson that relate to other content",
               s_b3_4 = "3.4 The teacher models by enacting, or thinking aloud",
               s_b4 = "CHECKS FOR UNDERSTANDING: Segment 1",
               s_b4_1 = "4.1 The teacher uses questions, prompts or other strategies to determine students's level of understanding",
               s_b4_2 = "4.2 The teacher monitors most students during independent/group work",
               s_b4_3 = "4.3 The teacher adjusts teaching to the level of the students",
               s_b5 = "FEEDBACK: Segment 1",
               s_b5_1 = "5.1 The teacher provides specific comments or prompts that help clarify students' misunderstandings",
               s_b5_2 = "5.2 The teacher provides specific comments or prompts that help identify students' successes",
               s_b6 = "CRITICAL THINKING: Segment 1",
               s_b6_1 = "6.1 The teacher asks open-ended questions",
               s_b6_2 = "6.2 The teacher provides thinking tasks",
               s_b6_3 = "6.3 The students ask open-ended questions or perform thinking tasks",
               s_c7 = "AUTONOMY: Segment 1",
               s_c7_1 = "7.1 The teacher provides students with choices",
               s_c7_2 = "7.2 The teacher provides students with opportunities to take on roles in the classroom",
               s_c7_3 = "7.3 The students volunteer to participate in the classroom",
               s_c8 = "PERSEVERANCE: Segment 1",
               s_c8_1 = "8.1 The teacher acknowledges students' effort",
               s_c8_2 = "8.2 The teacher has a positive attitude towards studens' challenges",
               s_c8_3 = "8.3 The teacher encourages goal-setting",
               s_c9 = "SOCIAL AND COLLABORATIVE SKILLS: Segment 1",
               s_c9_1 = "9.1 The teacher promotes students,?? collaboration through peer interaction",
               s_c9_2 = "9.2 The teacher promotes students' interpersonal skills",
               s_c9_3 = "9.3 Students collaborate with one another through peer interaction",
               enum_comments = "Additional comments by enumerator:"
)


teach_dta <- readxl::read_excel(path=file.path(download_folder, "TEACH_Final_Scores.xlsx"), sheet = "ALL_Scores", skip=2) %>%
  select(-c('...48'))


Hmisc::label(teach_dta) = as.list(var.labels[match(names(var.labels), names(var.labels))])
names(teach_dta) = names(var.labels)


#pull out school code from video clip name
teacher_pedagogy_segments <- teach_dta %>%
  separate(school_clip, into=c('school_code', 'clip'),
           sep= " Clip ") %>%
  mutate(school_code=as.numeric(str_trim(school_code)),
         clip=str_trim(clip)) %>%
  select(school_code, clip, starts_with("s_"))


#add weights and anonymize
teacher_pedagogy_micro <- df_anon('teacher_pedagogy_segments')                     


write_dta(teacher_pedagogy_micro, path = paste0(save_folder, "/micro/teacher_pedagogy_micro","_",country,"_",year,".dta"))    

```


## 4th grade file

```{r g4}

#read in 4th grade assessment level file
assess_4th_grade_dta<-read_dta(file.path(download_folder, "fourth_grade_assessment.dta"))

#Add school preamble info
assess_4th_grade_dta <- assess_4th_grade_dta %>%
  left_join(school_data_preamble) %>%
  select(preamble_info, everything()) 

#add weights and anonymize
fourth_grade_assessment_micro <- df_anon('assess_4th_grade_dta')                     


write_dta(fourth_grade_assessment_micro, path = paste0(save_folder, "/micro/fourth_grade_assessment_micro","_",country,"_",year,".dta")) 


```


## 1st grade file

```{r g1}
#read ecd data
ecd_dta<-read_dta(file.path(download_folder, "ecd_assessment_combined.dta"))

#Add school preamble info
ecd_dta <- ecd_dta %>%
  left_join(school_data_preamble) %>%
  select(preamble_info, everything())  

#add weights and anonymize
first_grade_assessment_micro <- df_anon('ecd_dta')                     


write_dta(first_grade_assessment_micro, path = paste0(save_folder, "/micro/first_grade_assessment_micro","_",country,"_",year,".dta")) 

```





 
 