---
title: "GEPD Microdata"
author: "Brian Stacy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.height = 6,
	fig.width = 8,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
library(haven)
library(vtable)
library(here)
library(readxl)
library(stringr)
library(Hmisc)
library(naniar)
library(lubridate)
library(skimr)
library(digest)
library(validate)
library(GGally)
library(Hmisc)
#Country name
country <-'MDG'
country_name <- "Madagascar"
year <- '2021'
school_file <-'EPDash.dta'
strata <- 
#########################
# File paths #
#########################
#The download_folder will be the location of where raw data is downloaded from the API
#The save_folder will be the location of where cleaned data is stored



if (str_to_lower(Sys.getenv("USERNAME")) == "wb469649" ){
  #project_folder  <- "//wbgfscifs01/GEDEDU/datalib-edu/projects/gepd"
  project_folder  <- "C:/Users/wb469649/WBG/HEDGE Files - HEDGE Documents/GEPD-Confidential/CNT/"
  download_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/raw/School", sep="/"))
  sampling_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/sampling", sep="/"))
  confidential_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/confidential/School", sep="/"))
  save_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/anonymized/School", sep="/"))
  backup_onedrive="no"
  save_folder_onedrive <- file.path(paste("C:/Users/wb469649/WBG/Ezequiel Molina - Dashboard (Team Folder)/Country_Work/",country_name,year,"Data/clean/School", sep="/"))
  
} else if  (str_to_lower(Sys.getenv("USERNAME")) == "wb577189" ){
  #project_folder  <- "//wbgfscifs01/GEDEDU/datalib-edu/projects/gepd"
  project_folder  <- "C:/Users/wb577189/OneDrive - WBG/GEPD-Confidential/CNT/"
  download_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/raw/School", sep="/"))
  sampling_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/sampling", sep="/"))
  confidential_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/confidential/School", sep="/"))
  save_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/anonymized/School", sep="/"))
  backup_onedrive="no"
  save_folder_onedrive <- file.path(paste("C:/Users/wb469649/WBG/Ezequiel Molina - Dashboard (Team Folder)/Country_Work/",country_name,year,"Data/clean/School", sep="/"))
  
}else {
  download_folder <- choose.dir(default = "", caption = "Select folder to open data downloaded from API")
  save_folder <- choose.dir(default = "", caption = "Select folder to save final data")

}


```


```{r functions}



#function to attach weights

df_weights_function <- function(dataset) {

  
  dataset %>%
    left_join(data_set_updated, by='s_ecole_code') %>%
        select(-ends_with(".x"), -ends_with(".y")) %>%
    mutate(ipw=if_else(is.na(ipw),median(ipw, na.rm=T), ipw)) %>%
    select(-one_of(colnames(data_set_updated[, -which(names(data_set_updated) == "urban_rural" | names(data_set_updated) == "province" | names(data_set_updated) == "district" |
                                                      names(data_set_updated) == "rural" | names(data_set_updated) == "public" | names(data_set_updated) == "students_enrolled"
                                                      | names(data_set_updated) == "ipw" | names(data_set_updated) == "ipw_school")])))
}



# anonymizer function

df_anon <- function(dataset) {
  temp<-get(dataset) 
    
    #add hashed school code if needed
        #add hashed school code if needed
    if ("s_ecole_code" %in% colnames(temp)) {
      temp <- temp %>%
        left_join(key) %>%
        select(hashed_school_code, everything())
    }
    
    
    #add on weights
    if ("s_ecole_code" %in% colnames(temp)) {
      temp <- df_weights_function(temp)
    }
    
    
    #Scrub names, geocodes
    temp <- temp %>%
      ungroup() %>%
      select(-starts_with('school_'), -one_of('m1s0q2_name', 'm1s0q2_code','m1s0q2_emis')) %>% # drop school names and address
      select(-starts_with('m1s0q9')) %>%
      select(-one_of('survey_time', 'lat','lon')) %>% #drop geo-codes
      select(-one_of('total_enrolled', 'm7saq8','m7saq10')) %>% 
      select(-one_of('m6_class_count')) %>% 
      select(-starts_with('enumerators_preload'), -one_of('m1s0q1_name', 'm1s0q1_name_other','m1s0q1_comments')) %>%  #get rid of enumerator names
      select(-one_of('m1saq1_first','m1saq1_last', 'm1saq2', 'm1saq2b')) %>% #drop principal names and phone numbers
      select(-contains('troster')) %>%
      select(-contains('name')) %>%
      select(-contains('_response')) %>%
      select(-contains('m2saq2')) %>%
      select(-contains('m6s1q1')) %>%
      select(-contains('m8s1q1')) %>%
      select(-contains('enumerators')) %>%
      select(-contains('m2saq2')) %>%
      select(-contains('m1saq1')) %>%
      select(-contains('phone')) %>%
      select(-contains('m1saq2')) %>%
      select(-contains('m7sb_troster')) %>%
      select(-contains('m3sb_troster')) %>%
      select(-contains('m3sb_etri')) %>%
      select(-contains('m5sb_troster')) %>%
      select(-contains('m6s1q1')) %>%
      select(-contains('m4saq1')) %>%
      select(-contains('m8s1q1')) %>%
      select(-contains('m4saq1_g2')) %>%
      select(-contains('comments')) %>%
      select(-contains('m1s0q1_name')) %>%
      select(-contains('m1s0q1_name_other')) %>%
      select(-contains('notekid')) %>%
      select(-one_of('s_fokontany_code', 's_adresse_etab', 's_latitude', 's_longitude', 's_ecole_code_r','s_m1a_01','s_m1a_03',
                     's_m1a_09','obs_enq', 
                     'enumerator_number','s_eleve_code', 's_ecole_code', 
                     'code_correcteur', 'id12_nom', 'nom_correcteur', 'id6a', 'id6a_nom',
                     's_m2ba1_01n'))
    
    #Drop any "other" responses to questions
    temp <- temp %>%
      select(-contains('_other'))
    
    
    
    #convert # of students in school to categorical
    if ("m1saq7" %in% colnames(temp)) {
    temp <- temp %>%
      mutate(students_enrolled=case_when(
        m1saq7<25 ~ 1,
        m1saq7>=25 &  m1saq7<50 ~ 2,
        m1saq7>=50 &  m1saq7<75 ~ 3,
        m1saq7>=75 &  m1saq7<100 ~ 4,
        m1saq7>=100 &  m1saq7<150 ~ 5,
        m1saq7>=150 &  m1saq7<300 ~ 6,
        m1saq7>=300 &  m1saq7<500 ~ 7,
        m1saq7>=500  ~ 8
      )) %>%
      mutate(students_enrolled=factor(students_enrolled, levels=c(1,2,3,4,5,6,7,8), labels = c("Under 25", "25-50", "50-75", "75-100", "100-150", "150-300", "300-500", "Over 500"))) %>%
      select(-m1saq7)
    }
    
    if ("m1saq8" %in% colnames(temp)) {
    temp <- temp %>%
      mutate(boy_students_enrolled=case_when(
        m1saq8<25 ~ 1,
        m1saq8>=25 &  m1saq8<50 ~ 2,
        m1saq8>=50 &  m1saq8<75 ~ 3,
        m1saq8>=75 &  m1saq8<100 ~ 4,
        m1saq8>=100 &  m1saq8<150 ~ 5,
        m1saq8>=150 &  m1saq8<300 ~ 6,
        m1saq8>=300 &  m1saq8<500 ~ 7,
        m1saq8>=500  ~ 8
      ))  %>%
      mutate(boy_students_enrolled=factor(students_enrolled, levels=c(1,2,3,4,5,6,7,8), labels = c("Under 25", "25-50", "50-75", "75-100", "100-150", "150-300", "300-500", "Over 500"))) %>%
      select( -m1saq8)      
    }
    
    #return data
    temp
}

```


```{r}
#Load data
load(paste0(confidential_folder, "/school_survey_data.Rdata"))
```




## Weights File

```{r}

# load sampling frame

sampling_frame <- read_excel(path=paste0(sampling_folder,'/Echantillons SDI V12.xlsx'))
sampling_frame_replacements <- read_excel(path=paste0(sampling_folder,'/Echantillons SDI V12.xlsx'), sheet = 'Écoles réserve')

sampling_frame <- sampling_frame %>%
  bind_rows(sampling_frame_replacements) %>%
  distinct(`CODE ETAB`, `NOM ETAB`, `CODE REGION`, `CODE COMMUNE 6`,.keep_all=TRUE)

sampling_strata_info <- read_csv(paste0(sampling_folder,'/school_strata_sampling.csv'))


#create straturm weights
sampling_strata_df <- sampling_strata_info %>%
  select(id, urban_sample, rural_sample, urban_4th, rural_4th) %>%
  pivot_longer(
    cols=c('urban_sample', 'rural_sample', 'urban_4th', 'rural_4th'),
    names_to='group',
    values_to='size'
  ) %>%
  mutate(sample=if_else(grepl('sample',group),'Sample_Size','Total_Size'),
         urban_rural=if_else(grepl('urban',group),'Urban','Rural')) %>%
  select(-group) %>%
  pivot_wider(
    names_from=sample,
    values_from=size
  ) %>%
  mutate(strata_prob= Total_Size/sum(Total_Size) )

# merge on the sampling info.  This dataframe contains probabilities each school was selected in a stratum
# strata were region and urban/rural.
data_set_updated <- school_dta_preamble %>%
  left_join(sampling_frame, by=c("s_etab_code"="CODE ETAB")) %>%
  mutate(province=s_commune_name,
           district=as.character(s_cisco_code),
           rural=s_urbain>=3, #rural coded as greater than 3
           urban_rural=if_else(rural==TRUE, "Rural", "Urban"),
           public=if_else(s_public==2, "Private", "Public"),
      students_enrolled=case_when(
        `Éleves Total`<25 ~ 1,
        `Éleves Total`>=25 &  `Éleves Total`<50 ~ 2,
        `Éleves Total`>=50 &  `Éleves Total`<75 ~ 3,
        `Éleves Total`>=75 &  `Éleves Total`<100 ~ 4,
        `Éleves Total`>=100 &  `Éleves Total`<150 ~ 5,
        `Éleves Total`>=150 &  `Éleves Total`<300 ~ 6,
        `Éleves Total`>=300 &  `Éleves Total`<500 ~ 7,
        `Éleves Total`>=500  ~ 8
      )) %>%
      mutate(students_enrolled=factor(students_enrolled, levels=c(1,2,3,4,5,6,7,8), labels = c("Under 25", "25-50", "50-75", "75-100", "100-150", "150-300", "300-500", "Over 500")),
           ipw_school=1/(`P1 (SDI)`/4), #divide by 4 because dashboard schools make up randomly selected 25% of sample 
                      ) %>%
  left_join(sampling_strata_df, by=c("CODE REGION"="id",
                                     "urban_rural"="urban_rural")) %>% # read in strata sampling info
  mutate(ipw=ipw_school*(1/strata_prob) # incorporate stratum weights
         
  )





key <- read_csv(file.path(confidential_folder, "EPDash_linkfile_hashed.csv"))

```

## School File

```{r school}

###########################
#read in school level file
###########################
school_micro_raw <- school_dta %>%
  group_by(school_code) %>%
  fill(everything(), .direction='downup') %>%
  slice(1) %>% 
  ungroup()


var.list <- sapply(school_dta, function(x) attr(x,"label"))
var.labels= unlist(var.list)

#add back labels
  
#add weights and anonymize
school_micro <- df_anon('school_micro_raw')                     

#school_micro <- Hmisc::upData(school_micro, labels = var.labels)

write_dta(school_micro, path = paste0(save_folder, "/micro/school_micro_",country,"_",year,".dta"))                           
```




## Teacher Questionnaire File

```{r}


#Add school preamble info
teacher_questionnaire <- teacher_questionnaire_dta

#add weights and anonymize
teacher_questionnaire_micro <- df_anon('teacher_questionnaire')                     

write_dta(teacher_questionnaire_micro, path = paste0(save_folder, "/micro/teacher_questionnaire_micro","_",country,"_",year,".dta"))    
```


## Teacher Absence File

```{r}
############################
#read in teacher roster file
############################


#Add school preamble info
teacher_absence_dta <- teacher_absence_final 

#add weights and anonymize
teacher_absence_micro <- df_anon('teacher_absence_dta')                     


write_dta(teacher_absence_micro, path = paste0(save_folder, "/micro/teacher_absence_micro","_",country,"_",year,".dta"))    
```


## Teacher Assessment File

```{r teacherassess}
#read in data from difference questionnaire.  This was done because the exams were graded back in the central office.


#add weights and anonymize
teacher_assessment_micro <- df_anon('teacher_assessment_dta')                     


write_dta(teacher_assessment_micro, path = paste0(save_folder, "/micro/teacher_assessment_micro","_",country,"_",year,".dta"))    
```





## 4th grade file

```{r g4}

#read in 4th grade assessment level file


#add weights and anonymize
fourth_grade_assessment_micro <- df_anon('assess_4th_grade_anon') %>%
  select(-contains("giraffe"))


write_dta(fourth_grade_assessment_micro, path = paste0(save_folder, "/micro/fourth_grade_assessment_micro","_",country,"_",year,".dta")) 


```


## 1st grade file

```{r g1}
#read ecd data


#add weights and anonymize
first_grade_assessment_micro <- df_anon('ecd_dta_anon')                     


write_dta(first_grade_assessment_micro, path = paste0(save_folder, "/micro/first_grade_assessment_micro","_",country,"_",year,".dta")) 

```





 
 