---
title: "GEPD Microdata"
author: "Brian Stacy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.height = 6,
	fig.width = 8,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
library(haven)
library(vtable)
library(here)
library(readxl)
library(stringr)
library(Hmisc)
library(naniar)
library(lubridate)
library(skimr)
library(digest)
library(validate)
library(GGally)
library(Hmisc)
#Country name
country <-'SLE'
country_name <- "Sierra Leone"
year <- '2022'
school_file <-'EPDash.dta'
#########################
# File paths #
#########################
#The download_folder will be the location of where raw data is downloaded from the API
#The save_folder will be the location of where cleaned data is stored



if (str_to_lower(Sys.getenv("USERNAME")) == "wb469649" ){
  #project_folder  <- "//wbgfscifs01/GEDEDU/datalib-edu/projects/gepd"
  project_folder  <- "C:/Users/wb469649/WBG/HEDGE Files - HEDGE Documents/GEPD-Confidential/CNT/"
  download_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/raw/School/", sep="/"))
  sampling_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/sampling", sep="/"))
  confidential_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/confidential/School", sep="/"))
  save_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/anonymized/School", sep="/"))
  backup_onedrive="no"
  save_folder_onedrive <- file.path(paste("C:/Users/wb469649/WBG/Ezequiel Molina - Dashboard (Team Folder)/Country_Work/",country_name,year,"Data/clean/School", sep="/"))
  
} else if  (str_to_lower(Sys.getenv("USERNAME")) == "wb577189" ){
  #project_folder  <- "//wbgfscifs01/GEDEDU/datalib-edu/projects/gepd"
  project_folder  <- "C:/Users/wb577189/OneDrive - WBG/GEPD-Confidential/CNT/"
  download_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/raw/School", sep="/"))
  sampling_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/sampling", sep="/"))
  confidential_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/confidential/School", sep="/"))
  save_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/anonymized/School", sep="/"))
  backup_onedrive="no"
  save_folder_onedrive <- file.path(paste("C:/Users/wb469649/WBG/Ezequiel Molina - Dashboard (Team Folder)/Country_Work/",country_name,year,"Data/clean/School", sep="/"))
  
}else {
  download_folder <- choose.dir(default = "", caption = "Select folder to open data downloaded from API")
  save_folder <- choose.dir(default = "", caption = "Select folder to save final data")

}


```


```{r functions}



#function to attach weights

df_weights_function <- function(dataset,scode, snumber, prov) {
  scode<-enquo(scode)  
  snumber<-enquo(snumber)
  prov<-enquo(prov)
  
  dataset %>%
    left_join(data_set_updated)  %>%
    mutate(province=idregion           ) 
}

# anonymizer function

df_anon <- function(dataset) {
  temp<-get(dataset) 
    
    #add hashed school code if needed
    if ("school_code" %in% colnames(temp)) {
      temp <- temp %>%
        left_join(key) %>%
        select(hashed_school_code, hashed_school_province, hashed_school_district, everything())
    }
    
    
    #add on weights
    if ("school_code" %in% colnames(temp)) {
      temp <- df_weights_function(temp, school_code, class4_combined, idregion)
    }
    
    #Scrub names, geocodes
    temp <- temp %>%
      select(-starts_with('school_'), -one_of('m1s0q2_name', 'm1s0q2_code','m1s0q2_emis')) %>% # drop school names and address
      select(-starts_with('m1s0q9')) %>%
      select(-one_of('survey_time', 'lat','lon')) %>% #drop geo-codes
      select(-one_of('total_enrolled', 'm7saq8','m7saq10')) %>% 
      select(-one_of('m6_class_count')) %>% 
      select(-starts_with('enumerators_preload'), -one_of('m1s0q1_name', 'm1s0q1_name_other','m1s0q1_comments')) %>%  #get rid of enumerator names
      select(-one_of('m1saq1_first','m1saq1_last', 'm1saq2', 'm1saq2b')) %>% #drop principal names and phone numbers
      select(-contains('troster')) %>%
      select(-contains('name')) %>%
      select(-contains('_response')) %>%
      select(-contains('m2saq2')) %>%
      select(-contains('m6s1q1')) %>%
      select(-contains('m8s1q1')) %>%
      select(-contains('enumerators')) %>%
      select(-contains('m2saq2')) %>%
      select(-contains('m1saq1')) %>%
      select(-contains('phone')) %>%
      select(-contains('m1saq2')) %>%
      select(-contains('m7sb_troster')) %>%
      select(-contains('m3sb_troster')) %>%
      select(-contains('m3sb_etri')) %>%
      select(-contains('m5sb_troster')) %>%
      select(-contains('m6s1q1')) %>%
      select(-contains('m4saq1')) %>%
      select(-contains('m8s1q1')) %>%
      select(-contains('m4saq1_g2')) %>%
      select(-contains('comments')) %>%
      select(-contains('m1s0q1_name')) %>%
      select(-contains('m1s0q1_name_other')) %>%
      select(-contains('notekid')) 
    
    #Drop any "other" responses to questions
    temp <- temp %>%
      select(-contains('_other'))
    
    
    
    #convert # of students in school to categorical
    if ("m1saq7" %in% colnames(temp)) {
    temp <- temp %>%
      mutate(students_enrolled=case_when(
        m1saq7<25 ~ 1,
        m1saq7>=25 &  m1saq7<50 ~ 2,
        m1saq7>=50 &  m1saq7<75 ~ 3,
        m1saq7>=75 &  m1saq7<100 ~ 4,
        m1saq7>=100 &  m1saq7<150 ~ 5,
        m1saq7>=150 &  m1saq7<300 ~ 6,
        m1saq7>=300 &  m1saq7<500 ~ 7,
        m1saq7>=500  ~ 8
      )) %>%
      mutate(students_enrolled=factor(students_enrolled, levels=c(1,2,3,4,5,6,7,8), labels = c("Under 25", "25-50", "50-75", "75-100", "100-150", "150-300", "300-500", "Over 500"))) %>%
      select(-m1saq7)
    }
    
    if ("m1saq8" %in% colnames(temp)) {
    temp <- temp %>%
      mutate(boy_students_enrolled=case_when(
        m1saq8<25 ~ 1,
        m1saq8>=25 &  m1saq8<50 ~ 2,
        m1saq8>=50 &  m1saq8<75 ~ 3,
        m1saq8>=75 &  m1saq8<100 ~ 4,
        m1saq8>=100 &  m1saq8<150 ~ 5,
        m1saq8>=150 &  m1saq8<300 ~ 6,
        m1saq8>=300 &  m1saq8<500 ~ 7,
        m1saq8>=500  ~ 8
      ))  %>%
      mutate(boy_students_enrolled=factor(students_enrolled, levels=c(1,2,3,4,5,6,7,8), labels = c("Under 25", "25-50", "50-75", "75-100", "100-150", "150-300", "300-500", "Over 500"))) %>%
      select( -m1saq8)      
    }
    
    #return data
    temp
}

```

```{r}
#list of key indicators

ind_list<-c('student_knowledge', 'math_student_knowledge', 'literacy_student_knowledge', 
            'student_proficient', 'student_proficient_70', 'student_proficient_75',
            'literacy_student_proficient', 'literacy_student_proficient_70', 'literacy_student_proficient_75',
            'math_student_proficient', 'math_student_proficient_70', 'math_student_proficient_75',
            'presence_rate','absence_rate', 'sch_absence_rate', 'student_attendance',
            'content_knowledge', 'math_content_knowledge', 'literacy_content_knowledge', 
            'content_proficiency',  'content_proficiency_70', 'content_proficiency_75',
            'literacy_content_proficiency',  'literacy_content_proficiency_70', 'literacy_content_proficiency_75',
            'math_content_proficiency',  'math_content_proficiency_70', 'math_content_proficiency_75',
            'teach_score','classroom_culture','instruction','socio_emotional_skills',
            'teach_prof','classroom_culture_prof','instruction_prof','socio_emotional_skills_prof',
            'ecd_student_proficiency', 'ecd_math_student_proficiency', 'ecd_literacy_student_proficiency', 'ecd_exec_student_proficiency', 'ecd_soc_student_proficiency',
            'ecd_student_knowledge', 'ecd_math_student_knowledge', 'ecd_literacy_student_knowledge', 'ecd_exec_student_knowledge', 'ecd_soc_student_knowledge',
            'inputs', 'blackboard_functional', 'pens_etc', 'textbooks', 'share_desk', 'used_ict', 'access_ict',
            'infrastructure','drinking_water', 'functioning_toilet', 'internet', 'class_electricity','disability_accessibility','disab_road_access', 'disab_school_ramp', 'disab_school_entr', 'disab_class_ramp', 'disab_class_entr', 'disab_screening',
            'operational_management', 'vignette_1', 'vignette_1_resp', 'vignette_1_finance', 'vignette_1_address', 'vignette_2', 'vignette_2_resp', 'vignette_2_finance', 'vignette_2_address', 
            'intrinsic_motivation', 'acceptable_absent', 'students_deserve_attention', 'growth_mindset', 'motivation_teaching',
            'instructional_leadership', 'classroom_observed', 'classroom_observed_recent', 'discussed_observation', 'feedback_observation', 'lesson_plan_w_feedback',
            'principal_knowledge_score', 'add_triple_digit_pknw', 'multiply_double_digit_pknw', 'complete_sentence_pknw', 'experience_pknw', 'textbooks_pknw', 'blackboard_pknw',
            'principal_management', 'sch_goals_exist','sch_goals_clear','sch_goals_relevant','sch_goals_measured',
            'teacher_attraction', 'teacher_satisfied_job', 'teacher_satisfied_status', 'better_teachers_promoted' ,'teacher_bonus', 'salary_delays',
            'teacher_selection_deployment', 'teacher_selection','teacher_deployment',
            'teacher_support', 'pre_service','practicum','in_service','opportunities_teachers_share',
            'teaching_evaluation', 'formally_evaluated', 'evaluation_content', 'negative_consequences','positive_consequences',
            'teacher_monitoring','attendance_evaluated' , 'attendance_rewarded' , 'attendence_sanctions', 'miss_class_admin',
            'sch_management_clarity', 'infrastructure_scfn','materials_scfn','hiring_scfn', 'supervision_scfn', 'student_scfn' , 'principal_hiring_scfn', 'principal_supervision_scfn',
            'standards_monitoring',
            'sch_monitoring', 'monitoring_inputs','monitoring_infrastructure','system_in_place','parents_involved',
            'sch_management_attraction', 'principal_satisfaction',
            'sch_selection_deployment', 
            'sch_support', 'prinicipal_trained','principal_training','principal_used_skills','principal_offered',
            'principal_evaluation', 'principal_formally_evaluated','principal_evaluation_multiple','principal_negative_consequences','principal_positive_consequences'
)

#attach derived indicators
attach(paste0(confidential_folder,"/school_survey_data.RData"))

```


## Weights File

```{r}
#read in the file on school weights
#Load original sample of schools
currentDate<-c("2022-10-07")
sample_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/sampling/", sep="/"))
data_set_updated <- read_csv(paste(sample_folder, '/school_weights_revised_', currentDate,  '.csv', sep="")
) %>%
  mutate(ipw=case_when(
    is.na(ipw) ~ median(ipw, na.rm=TRUE),
    is.infinite(ipw) ~ median(ipw, na.rm=TRUE),
    TRUE ~ ipw)
    ) %>%
  ungroup() %>%
  mutate(school_code=idemis_code,
         urban_rural=if_else(accessibility=="Easily accessible", "Urban", "Rural"),
         private=if_else(sch_owner %in% c("Government", "Community"), "Public", "Private")) %>%
  select(school_code, sch_owner, idregion, iddistrict,accessibility,school_districthq_distance, urban_rural,sch_owner,private,
         ipw) 



key <- read_csv(file.path(confidential_folder, "EPDash_linkfile_hashed.csv"))
```

## School File

```{r school}

###########################
#read in school level file
###########################
school_dta<-read_dta(file.path(download_folder, "EPDash.dta"))
vtable(school_dta)
#rename a few key variables up front
school_dta<- school_dta %>%
  mutate(enumerator_name_other= m1s0q1_name_other  ,
         enumerator_number=m1s0q1_name ,
         survey_time=m1s0q8,
         lat=m1s0q9__Latitude,
         lon=m1s0q9__Longitude,
         m7_teach_count_pknw=m7_teach_count, #this variable was mistakenly not tagged as pknw
         total_enrolled=m1saq7) %>%
  select(-starts_with("enumerators_preload")) %>% #bring in school codes that were created in separate stata program
  left_join((read_csv(file.path(download_folder, "emis_fixes.csv")) %>% select(interview__key, interview__id, school_code))) %>%
  mutate(school_code=as.numeric(school_code)) %>%
  filter(!is.na(school_code))



school_micro_raw <- school_dta %>%
  group_by(school_code) %>%
  fill(everything(), .direction='downup') %>%
  slice(1) %>% 
  ungroup()


var.list <- sapply(school_dta, function(x) attr(x,"label"))
var.labels= unlist(var.list)


#merge on derived indicators
school_micro_comb <- school_micro_raw %>%
  left_join(
    school_dta_short %>%
      select(school_code, ind_list)
  )

#add weights and anonymize
school_micro <- df_anon('school_micro_comb')                     

#school_micro <- Hmisc::upData(school_micro, labels = var.labels)

write_dta(school_micro, path = paste0(save_folder, "/micro/school_micro_",country,"_",year,".dta"))                           
```


```{r}
#create a file for matching to tecaher and student files

#list additional info that will be useful to keep in each indicator dataframe
preamble_info <- c( 'interview__key', 'school_code',
                   'school_name_preload', 
                   'school_province_preload', 'school_district_preload', 'school_emis_preload', 'school_emis_preload',
                   'school_info_correct', 'm1s0q2_name', 'm1s0q2_code', 'm1s0q2_emis',
                   'survey_time', 'lat', 'lon' , 'total_enrolled' , 'm7saq10'
                   )

drop_school_info <- c(

)


#create school database with just preamble info.  This will be useful for merging on school level info to some databases
school_data_preamble_temp <- school_dta %>%
  group_by(school_code) %>%
  select( preamble_info) %>%
  select(-interview__key) %>%
  summarise_all( ~(if(is.numeric(.)) mean(., na.rm = TRUE) else first(.))) 
  
school_data_preamble <- school_dta %>%
  group_by(interview__key) %>%
  select(interview__key, school_code) %>%
  left_join(school_data_preamble_temp)
```


## Teacher Questionnaire File

```{r}

teacher_questionnaire<-read_dta(file.path(download_folder, "questionnaire_roster.dta")) 

#Add school preamble info
teacher_questionnaire <- teacher_questionnaire %>%
  left_join(school_data_preamble) %>%
  select(preamble_info, everything())



#add weights and anonymize
teacher_questionnaire_micro <- df_anon('teacher_questionnaire')                     

write_dta(teacher_questionnaire_micro, path = paste0(save_folder, "/micro/teacher_questionnaire_micro","_",country,"_",year,".dta"))    
```


## Teacher Absence File

```{r}
############################
#read in teacher roster file
############################

teacher_absence_dta<-read_dta(file.path(download_folder, "TEACHERS.dta")) 

#Add school preamble info
teacher_absence_dta <- teacher_absence_dta %>%
  left_join(school_data_preamble) %>%
  select(preamble_info, everything()) 

#merge on derived indicators
teacher_absence_dta_comb <- teacher_absence_dta %>%
  left_join(
    teacher_absence_final %>%
      select(school_code, TEACHERS__id, contains(ind_list))
  ) %>%
  distinct(school_code, TEACHERS__id, .keep_all = TRUE)

#add weights and anonymize
teacher_absence_micro <- df_anon('teacher_absence_dta_comb')                     


write_dta(teacher_absence_micro, path = paste0(save_folder, "/micro/teacher_absence_micro","_",country,"_",year,".dta"))    
```


## Teacher Assessment File

```{r teacherassess}
#read in data from difference questionnaire.  This was done because the exams were graded back in the central office.
teacher_assessment_dta_raw <- read_dta(file.path(download_folder, "teacher_assessment_answers.dta")) %>%
  left_join(school_data_preamble) %>%
  select(preamble_info, everything()) 

#merge on derived indicators
teacher_assessment_dta_comb <- teacher_assessment_dta_raw %>%
  left_join(
    teacher_assessment_dta %>%
      select(school_code, teacher_assessment_answers__id, contains(ind_list))
  ) %>%
  distinct(school_code, teacher_assessment_answers__id, .keep_all = TRUE)


#add weights and anonymize
teacher_assessment_micro <- df_anon('teacher_assessment_dta_comb')                     


write_dta(teacher_assessment_micro, path = paste0(save_folder, "/micro/teacher_assessment_micro","_",country,"_",year,".dta"))    
```



## Teacher Pedagogy File

```{r pedg}



  
  teacher_pedagogy <- read_csv(paste0(download_folder,"/Teach scores Sierra Leone Final Final Final.csv")) %>%
  mutate(school_code=case_when(
    school_code==130101201  ~ 139103238,
    school_code==130501208   ~ 131301231, 
    school_code==220701216    ~ 220701211,  
    school_code==250401207    ~ 250401206,  
    school_code==410403466    ~ 420302687,  
    school_code==420505211     ~ 420505210, 
    school_code==420512204    ~ 420512209, 
    school_code==1110403201   ~ 110403201, 
    TRUE ~ school_code
  ))

teacher_pedagogy_segments <- teacher_pedagogy  %>%
    select(school_code, starts_with("s_"))
  
  #create sub-indicators from TEACH
  teacher_pedagogy_segments <- teacher_pedagogy_segments %>%
    mutate(classroom_culture=rowMeans(select(.,s_a1, s_a2)),
           instruction=rowMeans(select(.,s_b3, s_b4, s_b5, s_b6)),
           socio_emotional_skills=rowMeans(select(.,s_c7, s_c8, s_c9))
    ) 
  
  # Time on task - First measure (Yes/No on "Teacher provides learning activites to most students")
  # Generate a variable computing the proportion of times each teacher for each segment is providing a learning activity to students
  # We are only taking into account teachers for which we have at least 2 snapshots observed
  
  teacher_pedagogy_segments <- teacher_pedagogy_segments %>%
    mutate(nb_tt1=3-(is.na(s_0_1_1) + is.na(s_0_2_1) + is.na(s_0_3_1))) %>%
    mutate(timeontask1=if_else(nb_tt1>=2, rowMeans(select(.,s_0_1_1, s_0_2_1, s_0_3_1), na.rm=TRUE), NA_real_)) 
  
  #een tt_yes=rowmean(s_0_1_1_yes s_0_2_1_yes s_0_3_1_yes) if nb_tt1>=2
  #replace tt_yes=tt_yes*100
  #egen tt_no=rowmean(s_0_1_1_no s_0_2_1_no s_0_3_1_no) if nb_tt1>=2
  #replace tt_no=tt_no*100
  
  # Time on task - Second measure
  # Proportion of classes where a low number of students are on task, a medium number of students are on task
  teacher_pedagogy_segments <- teacher_pedagogy_segments %>%
    mutate(tot_low=rowSums(select(.,s_0_1_2,s_0_2_2,s_0_3_2) == 2),
           tot_medium=rowSums(select(.,s_0_1_2,s_0_2_2,s_0_3_2) == 3),
           tot_high=rowSums(select(.,s_0_1_2,s_0_2_2,s_0_3_2) == 4))
  
  # We count the number of snapshots observed (in case the observation lasted less than 15 minutes) and for which the teacher was providing a learning activity
  
  # For each of the variables "Low", "Medium" and "High", we create our own mean (in case the observation lasted less than 15 minutes or teacher was not providing a learning activity)
  # We are only taking into account teachers for which we have at least 2 snapshots observed
  
  teacher_pedagogy_segments <- teacher_pedagogy_segments %>%
    mutate(nb_tt2=3-(is.na(s_0_1_2) + is.na(s_0_2_2) + is.na(s_0_3_2)),
           tt_low=if_else(nb_tt2 >= 2, 100*tot_low/nb_tt2, NA_real_),
           tt_medium=if_else(nb_tt2 >= 2, 100*tot_medium/nb_tt2, NA_real_),
           tt_high=if_else(nb_tt2 >= 2, 100*tot_high/nb_tt2, NA_real_))
  
  
  final_indicator_data_PEDG <- teacher_pedagogy_segments %>%
    mutate(teach_score=(classroom_culture+instruction+socio_emotional_skills)/3,
           teach_prof=100*as.numeric(teach_score>=3),                      #rate teacher as proficient in teach and the subcomponents if they score at least 3
           classroom_culture_prof=100*as.numeric(classroom_culture>=3),
           instruction_prof=100*as.numeric(instruction>=3),
           socio_emotional_skills_prof=100*as.numeric(socio_emotional_skills>=3)) %>%
    filter(!is.na(teach_score)) 

#add weights and anonymize
teacher_pedagogy_micro <- df_anon('final_indicator_data_PEDG')                     


write_dta(teacher_pedagogy_micro, path = paste0(save_folder, "/micro/teacher_pedagogy_micro","_",country,"_",year,".dta"))    

```


## 4th grade file

```{r g4}

#read in 4th grade assessment level file
assess_4th_grade_dta_raw<-read_dta(file.path(download_folder, "fourth_grade_assessment.dta")) 
#Add school preamble info
assess_4th_grade_dta_raw <- assess_4th_grade_dta_raw %>%
  left_join(school_data_preamble) %>%
  select(preamble_info, everything()) 



#merge on derived indicators
assess_4th_grade_dta_comb <- assess_4th_grade_dta_raw %>%
  left_join(
    assess_4th_grade_anon %>%
      select(school_code, fourth_grade_assessment__id, contains(ind_list))
  ) %>%
  select(-ends_with('nogiraffe')) %>%
  distinct(school_code, fourth_grade_assessment__id, .keep_all = TRUE)


#add weights and anonymize
fourth_grade_assessment_micro <- df_anon('assess_4th_grade_dta_comb')                     


write_dta(fourth_grade_assessment_micro, path = paste0(save_folder, "/micro/fourth_grade_assessment_micro","_",country,"_",year,".dta")) 


```


## 1st grade file

```{r g1}
#read ecd data
ecd_dta<-read_dta(file.path(download_folder, "ecd_assessment.dta")) 
#Add school preamble info
ecd_dta <- ecd_dta %>%
  left_join(school_data_preamble) %>%
  select(preamble_info, everything())  %>%
  mutate(ecd_student_number=ecd_assessment__id)

#merge on derived indicators
ecd_dta_comb <- ecd_dta %>%
  left_join(
    ecd_dta_anon %>%
      select(school_code, ecd_student_number, contains(ind_list))
  ) %>%
  distinct(school_code, ecd_assessment__id, .keep_all = TRUE)


#add weights and anonymize
first_grade_assessment_micro <- df_anon('ecd_dta_comb')                     


write_dta(first_grade_assessment_micro, path = paste0(save_folder, "/micro/first_grade_assessment_micro","_",country,"_",year,".dta")) 

```


## AMPL-b

```{r}
ampl_b_dta <- read_csv(paste0(confidential_folder, "/ampl_b_sle_20220825.csv"))

ampl_b_micro <-df_anon('ampl_b_dta')  

write_dta(ampl_b_micro, path = paste0(save_folder, "/micro/ampl_b_micro","_",country,"_",year,".dta")) 

```



 
 