/*
File Authored by Brian Stacy
8/19/2019
*/

/* User should modify directory containing paradata */
gl wd "C:\Users\wb469649\OneDrive - WBG\Education Policy Dashboard\Survey Solutions\EPDash_8_Paradata_All"


*This code is autogenerated from Survey Solutions
insheet using "${wd}/paradata.tab", tab case names
label variable interview__id `"Unique 32-character long identifier of the interview"'
label variable order `"Sequential event number within each interview"'
label variable event `"Type of event happened"'
label variable responsible `"Login name of the person who initiated the event"'
label variable role `"System role of the person who initiated the event"'
label variable timestamp `"Date and time when the event happened"'
label variable offset `"Timezone offset relative to UTC"'
label variable parameters `"Event-specific parameters"'



gen timestamp1=subinstr(timestamp, "T"," ",.)

gen double tm=clock(timestamp1, "YMD hms")
format tm %tC
levelsof interview__id , local (res)
local counter=1
gen resp_id=.
foreach var in `res' {
replace resp_id=`counter' if interview__id=="`var'"
local counter=`counter'+1

}
tsset resp_id order
gen time_length=f.tm-tm

replace time_length=(f.tm-tm)/1000

*cleaning to split parameters field into question, module, response
split parameters, gen(mod) parse("||")
rename mod1 question
gen module = substr(question, 1,4)
rename mod2 response


*Tabulate time of each module
egen module_time=total(time_length), by(interview__id module)
gen module_time_min=module_time/60

*Summarize length of each module
tabstat module_time_min if parameters!="", by(module)
