---
title: "AMPL-b Analysis"
author: "Brian Stacy"
date: "8/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.height = 6,
	fig.width = 8,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
library(haven)
library(vtable)
library(here)
library(readxl)
library(stringr)
library(Hmisc)
library(naniar)
library(lubridate)
library(skimr)
library(digest)
library(validate)
library(GGally)

#Country name
country <-'SLE'
country_name <- "Sierra Leone"
year <- '2022'

#########################
# File paths #
#########################
#The download_folder will be the location of where raw data is downloaded from the API
#The save_folder will be the location of where cleaned data is stored



if (str_to_lower(Sys.getenv("USERNAME")) == "wb469649" ){
  #project_folder  <- "//wbgfscifs01/GEDEDU/datalib-edu/projects/gepd"
  project_folder  <- "C:/Users/wb469649/WBG/HEDGE Files - HEDGE Documents/GEPD-Confidential/CNT/"
  download_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/raw/School", sep="/"))
  sampling_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/sampling", sep="/"))
  confidential_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/confidential/School", sep="/"))
  save_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/anonymized/School", sep="/"))
  backup_onedrive="no"
  save_folder_onedrive <- file.path(paste("C:/Users/wb469649/WBG/Ezequiel Molina - Dashboard (Team Folder)/Country_Work/",country_name,year,"Data/clean/School", sep="/"))
  
} else if  (str_to_lower(Sys.getenv("USERNAME")) == "wb577189" ){
  #project_folder  <- "//wbgfscifs01/GEDEDU/datalib-edu/projects/gepd"
  project_folder  <- "C:/Users/wb577189/OneDrive - WBG/GEPD-Confidential/CNT/"
  download_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/raw/School", sep="/"))
  sampling_folder <-file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/sampling", sep="/"))
  confidential_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/confidential/School", sep="/"))
  save_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/anonymized/School", sep="/"))
  backup_onedrive="no"
  save_folder_onedrive <- file.path(paste("C:/Users/wb469649/WBG/Ezequiel Molina - Dashboard (Team Folder)/Country_Work/",country_name,year,"Data/clean/School", sep="/"))
  
}else {
  download_folder <- choose.dir(default = "", caption = "Select folder to open data downloaded from API")
  save_folder <- choose.dir(default = "", caption = "Select folder to save final data")

}


```

```{r data}



#read in weights
currentDate<-c("2022-08-25")
sample_folder <- file.path(paste(project_folder,country,paste(country,year,"GEPD", sep="_"),paste(country,year,"GEPD_v01_RAW", sep="_"),"Data/sampling/", sep="/"))

sle_weights <- read_csv(paste(sample_folder, '/amplb_weights_revised_', currentDate,  '.csv', sep="")) %>%
  mutate(school_weight=case_when(
    is.na(school_weight) ~ median(school_weight, na.rm=TRUE),
    is.infinite(school_weight) ~ median(school_weight, na.rm=TRUE),
    TRUE ~ school_weight)
    ) %>%
  ungroup() %>%
  mutate(school_code=idemis_code,
         urban_rural=if_else(accessibility=="Easily accessible", "Urban", "Rural")) %>%
  select(school_code, sch_owner, idregion, iddistrict, urban_rural,
         contains("strata"), contains("weight")) 

#read in database that fixes emis codes

emis_fixes <- read_csv(file.path(download_folder, "emis_fixes.csv")) %>%
  filter(order!=89) %>% #manual fix for school that was duplicated
  select(school_code, school_name_preload, school_province_preload, school_district_preload, school_emis_preload) %>%
  group_by(school_code,school_name_preload ) %>%
  summarise(across(everything(), first)) %>%
  filter(!(is.na(school_code) | school_code=="Blank interview"))

#read in the ampl-b dataset

ampl_b_school_df_raw <- read_dta(file=paste0(download_folder, "/ampl_dash_5_STATA_All/ampl_dash.dta")) %>%
  bind_rows(read_dta(file=paste0(download_folder, "/ampl_dash_3_STATA_All/ampl_dash.dta"))) %>%
  select(-starts_with("enumerators_preload")) 

ampl_b_school_df_blank <- ampl_b_school_df_raw %>%
  filter(school_name_preload=="Blank interview" | school_name_preload=="BAPTIST COMMUNITY  PRIMARY  SCHOOL"|
            school_name_preload=="SUSAN MANS MEMORIAL BAPTIST PRIMARY SCHOOL" |
            school_name_preload== "HAMEED ISLAMIC PRIMARY SCHOOL" |
           m1s0q2_name=="EVENGICAL MODEL PRIMARY SCHOOL, MAKAREMBAY, MAFONDA ROPOLLON." | 
             m1s0q2_name=="WESLEYAN CHURCH OF SIERRA LEONE PRIMARY SCHOOL KATHANTHA  VILLAGE SELLA LIMBA CHIEFDOM. KAYIMBOR 1 SECTION. KARENE DISTRICT") %>% 
  #filter(!(school_name_preload=="Blank interview" )) %>%
  mutate( #manually fix some nonmatches
    school_code=case_when(
      interview__key=="16-59-57-90" ~ 210402223,
      interview__key=="09-62-39-72" ~ 131301209,
      interview__key=="80-00-85-21" ~ 129103244,
      interview__key=="54-00-25-48" ~ 220304214,
      interview__key=="25-13-11-75" ~ 129103239,
      interview__key=="84-15-81-26" ~ 240406215,
      interview__key=="91-16-77-01" ~ 330701203,
      interview__key=="35-14-09-17" ~ 240706204,
      interview__key=="08-27-75-16" ~ 311001209,
      interview__key=="63-07-55-51" ~ 420516207,
      interview__key=="27-87-18-91" ~ 220502208,
      interview__key=="94-67-65-92" ~ 240801212,
      interview__key=="01-20-94-75" ~ 210402223,
      interview__key=="33-95-78-41" ~ 131002203,
      interview__key=="74-52-39-05" ~ 131002203,
      interview__key=="74-77-58-12" ~ 131002203,
      interview__key=="66-68-84-70" ~ 130402206,
      interview__key=="22-44-65-21" ~ 130402206,
      interview__key=="04-51-77-93" ~ 130402206,
      
      interview__key=="15-54-30-68" ~ 210501223,
      interview__key=="87-10-36-97" ~ 211205205,
      interview__key=="72-34-28-97" ~ 240801212,
      interview__key=="49-14-32-95" ~ 420516207
    )
  ) %>%
  mutate(school_code=as.numeric(school_code)) %>%
  select( school_code, interview__id, interview__key) %>%
  left_join(sle_weights)

ampl_b_school_df_other <- ampl_b_school_df_raw %>%
  filter(!(school_name_preload=="Blank interview" | school_name_preload=="BAPTIST COMMUNITY  PRIMARY  SCHOOL"|
            school_name_preload=="SUSAN MANS MEMORIAL BAPTIST PRIMARY SCHOOL" |
            school_name_preload== "HAMEED ISLAMIC PRIMARY SCHOOL" |
           m1s0q2_name=="EVENGICAL MODEL PRIMARY SCHOOL, MAKAREMBAY, MAFONDA ROPOLLON." | 
             m1s0q2_name=="WESLEYAN CHURCH OF SIERRA LEONE PRIMARY SCHOOL KATHANTHA  VILLAGE SELLA LIMBA CHIEFDOM. KAYIMBOR 1 SECTION. KARENE DISTRICT")) %>%
  mutate(across(is.character,~if_else(.=="NA",as.character(NA),.))) %>%
  left_join(emis_fixes) %>%
  mutate(school_code=as.numeric(school_code)) %>%
  select( school_code, everything()) %>%
  left_join(sle_weights)

ampl_b_school_df <- ampl_b_school_df_blank %>%
  bind_rows(ampl_b_school_df_other)

ampl_b_responses_df <- read_dta(file=paste0(download_folder, "/ampl_dash_5_STATA_All/questionnaire_roster.dta")) %>%
  bind_rows(read_dta(file=paste0(download_folder, "/ampl_dash_3_STATA_All/questionnaire_roster.dta"))) %>%
  left_join(ampl_b_school_df) %>%
  arrange(school_code, student_name) %>%
  select(colnames(ampl_b_school_df), everything()) %>%
  distinct(school_code,  m3sb_troster, .keep_all=TRUE)

write_excel_csv(ampl_b_responses_df, paste0(confidential_folder, "/ampl_b_responses_df.csv"))

```




