
---
title: "Data Quality Checks - AMPL-b"
author: "Adrien Ciret"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load relevant libraries
library(tidyverse)
library(haven)
library(plotly)
library(naniar)
library(crosstalk)
library(leaflet)
library(Hmisc)
library(DT)
library(mice)
library(stargazer)
library(skimr)
library(knitr)
library(kableExtra)

#Load the data
#read in school level file
save_folder <- 'C:/Users/wb577189/OneDrive - WBG/My files/Dashboard (Team Folder)/Country_Work/Pakistan_all/2021/Data/01. Pilot/clean/amplb/'

final <- read.csv(paste0(save_folder, "amplb_pak_pilot2.csv")) %>% rename(student_count = `Number.of.students.for.which.the.assessment.was.entered`)
```


## Description of fieldwork overall

```{r overall,  echo=FALSE}

# of schools
# of booklets (per type)
# map them

final  %>% filter(!is.na(.)) %>%  summarise(
  
  `Number of schools covered` = n_distinct(`school_emis_preload`),
  `Total booklets entered` = n(),
  `Number of booklet 1` = sum(type_booklet==1),
  `Number of booklet 2`= sum(type_booklet==2),
  `Average number of students` = round(mean(student_count), digits = 0),
  `Percentage of boys`= round(sum(ST01==2)/nrow(.)*100, digits = 0),
  `Percentage of girls`= round(sum(ST01==1)/nrow(.)*100, digits = 0)


  
)  %>%  pivot_longer(cols=everything(), names_to = "Variable", values_to= "Value") %>% flextable::flextable() %>% flextable::autofit()




```
## Description of fieldwork per school

```{r per schools,  echo=FALSE}


perschool<- final %>% group_by(school_emis_preload) %>%  summarise(
  
  `Number of booklet 1` = sum(type_booklet==1),
  `Number of booklet 2`= sum(type_booklet==2),
  `Average number of students` = round(mean(student_count), digits = 0),
  `Number of boys`= sum(ST01==2),
  `Number of girls`= sum(ST01==1)


  
) %>% 
  mutate(`Percentage of boys` = round(`Number of boys`/(`Number of boys` + `Number of girls`)*100, digits = 0),
         `Percentage of girls` = round(`Number of girls`/(`Number of boys` + `Number of girls`)*100, digits = 0))

perschool%>% flextable::flextable() %>% flextable::autofit() 



```


## Missing interviews

```{r, echo=FALSE}
assignments <- read.table( "C:/Users/wb577189/OneDrive - WBG/My files/Dashboard (Team Folder)/Country_Work/Pakistan_all/2021/Survey solutions/GEPD/AMPL-b/amplb_assignment_pak_pilot.txt", sep="\t", header=TRUE)

school_completed <- final %>% filter(`school_emis_preload`!= "Blank interview") %>% pull(`school_emis_preload`)

'%!in%' <- function(x,y)!('%in%'(x,y))


missing_schools <- assignments %>% filter(school_emis_preload %!in% school_completed)

missing_schools %>% 
  select(-school_address_preload, -school_code_preload) %>% 
  filter(school_emis_preload!= "Blank interview") %>% 
  rename(`Enumerator responsible` = X_responsible,
         `Number of questionnaire expected`= X_quantity) %>% 
  flextable::flextable() %>% flextable::autofit()
```




## Mapping of the fieldwork

```{r map,  echo=FALSE}

school_map <- read.csv("C:/Users/wb577189/OneDrive - WBG/My files/Dashboard (Team Folder)/Country_Work/Pakistan_all/2021/Data/01. Pilot/clean/final_complete_school_data.csv") %>% select(school_name_preload, school_province_preload, school_district_preload, school_emis_preload, lat, lon) %>%
  filter(!str_detect(school_emis_preload, "Blank interview")) %>% mutate(school_emis_preload=as.numeric(school_emis_preload)) %>%  right_join(perschool %>% rename(school_emis_preload=`school_emis_preload`)) %>% filter(!is.na(.))


#create icons
icons2 <- awesomeIcons(
  icon = 'graduation-cap',
  iconColor = 'white',
  library = 'fa',
  markerColor = 'blue'
)


map2 <- function(df_input) {    leaflet(df_input, height=1200, width=1020) %>% 
  addTiles()  %>%
  addAwesomeMarkers(lng=~lon, lat= ~lat, icon=icons2,
                    popup = paste("Name: ", school_map$school_name_preload, " <br>",
                                  "Province: ", school_map$school_province_preload, " <br>",
                                  "District: ", school_map$school_district_preload, " <br>",
                                  "EMIS Code: ", school_map$school_emis_preload, " <br>",
                                  "<font color='red' > Description ", " <br> <font color='black' >",
                                  "Number of booklet 1 : ", round(school_map$`Number of booklet 1`, digits=2), "<br>",
                                  "Number of booklet 2 : ", round(school_map$`Number of booklet 1`, digits=2), "<br>",
                                  "Number of students : ", round(school_map$`Average number of students`, digits=2), "<br>",
                                  "Percentage of boys : ", round(school_map$`Percentage of boys`, digits=2), "% <br>",
                                  "Percentage of girls : ", round(school_map$`Percentage of girls`, digits=2), "% <br>"



                                  ) )  

}


map2(school_map)

```

