
---
title: "Data Quality Checks - TEACH ECE"
author: "Adrien Ciret"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load relevant libraries
library(tidyverse)
library(haven)
library(plotly)
library(naniar)
library(crosstalk)
library(leaflet)
library(Hmisc)
library(DT)
library(mice)
library(stargazer)
library(skimr)
library(knitr)
library(kableExtra)
#Clean data files downloaded from API
#Written by Adrien Ciret 01/06/2022

#load relevant libraries

library(skimr)
library(naniar)
library(vtable)
library(digest)
library(tidyverse)
library(haven)
library(stringr)
library(Hmisc)
library(sjlabelled)
#NOTE:  The R script to pull the data from the API should be run before this file



#Create function to save metadata for each question in each module
makeVlist <- function(dta) { 
  varlabels <- sapply(dta, function(x) attr(x,"label"))
  vallabels <- sapply(dta, function(x) attr(x,"labels"))
  tibble(name = names(varlabels),
         varlabel = varlabels, vallabel = vallabels) 
}



#Country name and year of survey
country <-'Pakistan_all'
country_name <- "Pakistan_all"
year <- '2021'



  project_folder  <- "C:/Users/wb577189/OneDrive - WBG/My files/Dashboard (Team Folder)/Country_Work/"
  download_folder <-file.path(paste(project_folder,country_name,year,"Data/01. Pilot/raw/teach_ece", sep="/"))
 


############################
#read in TEACH ECE file
############################

teachece<-read_dta(file.path(download_folder, "TEACH_ECE_PAK.dta"))
```


```{r, include=FALSE}

## If blank interview, then we look for the replacing information


teachece <- teachece %>% 
  mutate(
    school_name_preload = if_else(school_name_preload=="Blank interview" & school_info_correct!=1, m1s0q2_name, school_name_preload),
    school_emis_preload = if_else(school_emis_preload=="Blank interview" & school_info_correct!=1, m1s0q2_emis, school_emis_preload)
    
    
  ) %>% 
  
  select(ends_with("_preload"), ends_with("_Latitude"), ends_with("_Longitude"))
```



## Missing interviews

```{r overall,  echo=FALSE}

# of schools
# of booklets (per type)
# map them

assignments <- read.table( "C:/Users/wb577189/OneDrive - WBG/My files/Dashboard (Team Folder)/Country_Work/Pakistan_all/2021/Survey solutions/TEACH_ECE/teach_assignment_pak_pilot.txt", sep="\t", header=TRUE)

school_completed <- teachece %>% filter(school_emis_preload!= "Blank interview") %>% pull(school_emis_preload)

'%!in%' <- function(x,y)!('%in%'(x,y))


missing_schools <- assignments %>% filter(school_emis_preload %!in% school_completed)

missing_schools %>% 
  select(-school_address_preload, -school_code_preload) %>% 
  filter(school_emis_preload!= "Blank interview") %>% 
  rename(`Enumerator responsible` = X_responsible,
         `Number of questionnaire expected`= X_quantity) %>% 
  flextable::flextable() %>% flextable::autofit()




```

## Mapping of the fieldwork

```{r map,  echo=FALSE}

school_map <- teachece %>% rename(
  
  lat = m1s0q9__Latitude,
  lon=m1s0q9__Longitude
)


#create icons
icons2 <- awesomeIcons(
  icon = 'graduation-cap',
  iconColor = 'white',
  library = 'fa',
  markerColor = 'blue'
)


map2 <- function(df_input) {    leaflet(df_input, height=1200, width=1020) %>% 
  addTiles()  %>%
  addAwesomeMarkers(lng=~lon, lat= ~lat, icon=icons2,
                    popup = paste("Name: ", school_map$school_name_preload, " <br>",
                                  "Province: ", school_map$school_province_preload, " <br>",
                                  "District: ", school_map$school_district_preload, " <br>",
                                  "EMIS Code: ", school_map$school_emis_preload, " <br>"

                                  ) )  

}


map2(school_map)

```

